### ISSUE TITLE
[Suggestion] Greenhouse glass near useless in last update

### ISSUE THREAD

**Issue by RoyalCube** [Ellpeck/ActuallyAdditions#1008]
I have read the patch notes and know that the block isn't a tile entity anymore and that this would affect the grow speed, but at this point it is near useless. Especially for the time and resources needed to craft them. For me there is no noticable diffrence with or without them. So perhaps it's a good idea to bump up the grow speed or cheapen the recipe?

**Comment by Shadows-of-Fire** [comment]
There might be a way to return the speed aspect of them, but to do that would require a break/replace of every single block anyone has...
Certainly the slower growth rate is an issue, it will be addressed soon.

**Comment by Shadows-of-Fire** [comment]
The recipe will now use a normal palis crystal block, instead of the empowered version.  The decrease in speed is honestly not the most desired effect, but to change it would reintroduce the issues that were present before.  

While I would like it to be fast, the cost that comes with it is too much.
