### ISSUE TITLE
Villager Confi Option

### ISSUE THREAD

**Issue by 9-tailed** [Ellpeck/ActuallyAdditions#1066]
Hello,

just wanted to try this Mod, but I found a little bug.
I use a mod that changes this terrible vanilla villagers to something nice.
But every mod that adds own villager spawns back vanilla villager, so I have to disable them in the mods configs. I did the same with your mod, but the villager is still spawning. 

Hope you can fix this, till then I remove the mod again.

**Comment by Quarris** [comment]
Wait the wat? You're removing the mod because vanilla villagers look bad? What kind of reason is that?!

**Comment by Ellpeck** [comment]
This is the most ridiculous issue I have ever received

I mean me too thanks

**Comment by Shadows-of-Fire** [comment]
Right...  The config works, and if it's actually turned off the villagers never get registered to the game.  You should probably go check you actually hit save on the config file.

**Comment by 9-tailed** [comment]
Wow thanks, what nice replys.

Don't know whats so funny with that. I plan a project with villagers and this constant terrible sound just would drive me crazy. 

@Shadows-of-Fire I know how to use a config option. I even checked if the value is written right to the config file. There everything looks fine.

I just rechecked the issue on a vanilla minecraft. Created a world, found a village with with one of your villagers. Turn of the config value und created a second world with the same seed. Villager is there again. Seed to test with a village right next to spawn: 3520361457637585547.

**Comment by Shadows-of-Fire** [comment]
The provided seed does not contain any AA villager buildings when the configuration is turned off.

**Comment by Quarris** [comment]
First of all, stop complaining that you worded the issue very badly by saying something like 'Mod bad cuz villager suck'.
Second, I tested with the seed, no AA villagers spawn on the seed.
Third, Make sure you did the configs correct, there are 2 villager config options, so make sure you disable both. If that doesnt work, check and make sure that the issue still happens if only AA is installed on the instance, since some other mod for some bizarre reason may somehow manage to reenable the configs O.o.
Else fuck knows.

**Comment by Ellpeck** [comment]
Oof.

**Comment by Ellpeck** [comment]
Oh, just as a reminder in case this is actually about that: 
In case you play in a version below 1.12, then that one's not supported.
