### ISSUE TITLE
(BUG) Traveller's Sack fully resets upon login

### ISSUE THREAD

**Issue by Vaygrim** [Ellpeck/ActuallyAdditions#1139]
Minecraft 1.12.2
Forge 2705
ActuallyAdditions 1.12.2-r136-hotfix7

I've got a pack called "Coop Life 2", in it I've been making use of an AA Traveller's Sack with a Filter.. to collect the various drops I generate automatically (I'm a chicken, it's a long story). This worked fine prior to the _1.12.2-r136-hotfix7_ update. As of that update happening, logging into the server results in my Traveller's Sack being fully reset back to its starting state. Filter vanishes, contents vanish, all previous settings vanish.

I'd provide further info if needed, but since this isn't a "crash inducing" problem.. there's no crash log to include.

Help? <3

**Comment by Shadows-of-Fire** [comment]
Hm.  I can't actually reproduce this.  The change wasn't made in hotfix-7, it was made in (i believe) hotfix-2, but the change was made to only sync when the gui is open to avoid crashing due to NBT packet size.  
However, if something was crashing during the sync in the container, it might just fail to sync entirely.  A full game log from the instance that it happened will be necessary to figure this out.
