### ISSUE TITLE
esd interactions with hopper bonsai

### ISSUE THREAD

**Issue by StrommKral** [Ellpeck/ActuallyAdditions#1188]
Placing a hopper Bonsai Slime tree on an ESD, fed into a crate, you only get slime blocks, you should get slime balls, saplings and leaves. Not tested with other trees.

**Comment by Shadows-of-Fire** [comment]
Alright, so from my understanding of the hopping bonsai pot, this isn't actually a bug.

The ESD has a one-slot inventory in which it tries to export from every tick.
The hopping bonsai pot tries to export the full amount of items and discards any remaining if there is not space in the inventory.
Since there's only the one slot in the ESD, this means the bonsai discards all items except for the first.
