### ISSUE TITLE
[Suggestion] New drill Upgrades

### ISSUE THREAD

**Issue by MrRiegel** [Ellpeck/ActuallyAdditions#120]
Void Upgrade - No items will drop (or at least no cobble, dirt, gravel)
or you add a slot for the item filter into the drill GUI
Veinminer Upgrade
Furnace Upgrade - cooking the drops if possible

**Comment by Rated01010010** [comment]
Do the upgrades affect how much energy the drill consumes?

**Comment by Ellpeck** [comment]
The void upgrade is now covered by the void bag that you can just use instead, and I don't really want to make any more upgrades for the drill anyways, as the GUI is already pretty full usually, and I don't want to make it any bigger because otherwise you could combine too many upgrades and upgrade tiers.
Sorry.
