### ISSUE TITLE
Crusher (and possibly other machines) lag issue

### ISSUE THREAD

**Issue by LatvianModder** [Ellpeck/ActuallyAdditions#1210]
When power is close to 0 and machine is working, constantly changing states becomes very laggy. Here is a video: https://youtu.be/V6Dl5A-Mz4k

**Comment by Quarris** [comment]
That is not an issue , the reason why it hsppens is because the machine uses more power per tock than you can provide it, so as soon as it gets power is then starts working, uses it and stop working. Its not really something that can be "fixed" effectiveltly on the modders part. Simply give it more power

**Comment by LatvianModder** [comment]
Could only update state once a second or something. Or pause updates for a second if the state just changed

**Comment by Quarris** [comment]
Even though I believe it is possible, I do not think that it is an ideal scenario is majority of the cases. I'm not the developer though, but I don't think that it is something that would be changed.

**Comment by Shadows-of-Fire** [comment]
Resolving this in the most reasonable way possible which doesn't sacrifice the fact that the machines should always update their state when on/off: A redstone signal will now force them into the "on" state, regardless of actual use.
