### ISSUE TITLE
[Suggestion] Hide particle effects on phantomface connected blocks.

### ISSUE THREAD

**Issue by pneumaticLance** [Ellpeck/ActuallyAdditions#1232]
Phantomfaces are amazing at hiding blocks, however it kinda defeats its own purpose when the connected blocks emit particle effects. This becomes an eyesore when there's multiple blocks connected with phantomfaces.

While it can be disable by turning off the particles in the minecraft settings, however doing so will also affect other mods. I suggest only showing the particle effect when the player is holding the Phantom Connector, or just a config option to toggle it off.

**Comment by Tntdruid** [comment]
Should be a config setting for this

**Comment by Ellpeck** [comment]
The purpose of phantomfaces isn't to hide anything, but to allow for more connections to be applied to the same block. I'm sorry, but I don't like this idea.

**Comment by pneumaticLance** [comment]
"The Phantomface should be used when, for example, wanting to input items into a machine that doesn't have enough space for the amount of cables you need around it, **or when you want it to look nice in a room without needing any cables or other blocks around it.** " ~Actually Additions WebManual

Ok, I just thought having the connected machine/block emitting particles breaks the illusion of looking nice. Didn't know we have moved away from that notion.

**Comment by JHawkley** [comment]
You should reconsider; the particles are annoying and an eyesore when you're trying to maintain certain aesthetics.  A constant reminder of the fact that a block is connected to a Phantomface is neither necessary nor desired.

The information the particles provide is only really useful when manipulating a system involving a Phantomface; they do not need to be constantly applied to the linked block.

The particles also provide little **useful** information; they only seem to convey to the player, "this block is connected to SOME Phantomface within a range of 144 blocks."  If you have many linked blocks and/or Phantomfaces arranged in an array, this becomes a nightmare when maintenance needs to be done on the phantom network.

When you coded in this particle effect, what exactly did you expect it to add to the Phantomface?  I'm having trouble understanding it's use or purpose.

Showing some effect linking the machine to its Phantomface, like a beam of portal particles, while holding the Phantom Connector would be far more useful.

Otherwise, adding a capability where the particles could be toggled on and off would also be handy.  The particles for a particular Phantomface could be toggled on to highlight the specific block it is linked to, then toggled off once they're no longer useful.

Both of these suggestions would add clear purpose to including such a particle effect and they would only need to interfere with aesthetics when the information they provide is contextually useful.
