### ISSUE TITLE
Issue - 1.12.2. Memory Leak Found

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ellpeck/ActuallyAdditions#1260]
So for some reason when I add actually additions to my modpack it has a very bad memory leak feel free to see for yourself by adding it to this pack https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/releases/tag/mc-1.12.2-IfYouWantItWorkForIt-0008

Get the pack from here
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench

**Comment by P3rf3ctXZer0** [comment]
@Shadows-of-Fire thanks by the way for the amazing Java args. I have a 45% performance increase from your Java 8 Research.

**Comment by P3rf3ctXZer0** [comment]
@Shadows-of-Fire thank you so much by the way for your Java 8 Insight your Java args have given my pack a 45% increase and damn near made microstuttering vanish.

**Comment by P3rf3ctXZer0** [comment]
So ingame f3 won't tell you anything - watch task manager.

**Comment by Shadows-of-Fire** [comment]
AA does not have any memory leaks within it.  It adds a lot of stuff, and game objects use quite a bit of memory, but there's nothing leaking.

A memory leak is when an offending piece of code causes memory usage to increase to infinity due to not properly deallocating something, not simply a large increase in memory usage.

**Comment by P3rf3ctXZer0** [comment]
That is what your mod does ... sorry if you took personal offense. I have a 101 mods running at 3GB with your mod I broke at 6gb. in 40 mins because it has a memory leak. I mean I just switched to extra utilities since you want to ignore this.
