### ISSUE TITLE
Damaged Knife not recognized By recipes

### ISSUE THREAD

**Issue by Wolfwing** [Ellpeck/ActuallyAdditions#168]
I'm running Version 1.10.2-r54

After using the knife once to craft BioMash it is no longer recognized as valid for the recipe due to the damage it sustained.

The recipe I was using was 4 seeds (the one for Wheat) plus the knife.

**Comment by Ellpeck** [comment]
What the heck, I fixed this like 20 times already, how does this keep breaking?

**Comment by Ellpeck** [comment]
What crafting table are you using? Because I can't reproduce it in a vanilla one.

**Comment by 7OOTnegaTerces** [comment]
I had this same problem too.  I eventually realized that it was caused by the same bug that crashes the ore dictionary.  Look up any recipe in the guidebook, like the wood casing, that involves interchangeable ingredients and the ore dictionary crashes, so that, for instance, you can only craft chests using oak wood planks and no other type.  Actually, now that I reflect on this issue, I think what's really going on is that the recipes start caring about meta data when they shouldn't.  For instance, once this bug is triggered, the knife will only work the first time, while it's still brand new, but not once it's meta data has changed and it has some damage (ditto for other tools used in recipes, like the Building Brick mod's saw).  It's also the meta data that differentiates the different types of wood, etc.

**Comment by 7OOTnegaTerces** [comment]
Please add this fix to the 1.9 version, I'm still using it!!!

**Comment by Ellpeck** [comment]
Sorry, I don't support the 1.9 version anymore :(
The problem was that I wasn't copying ItemStacks where I should have :)
