### ISSUE TITLE
Crash when using Mek cables with AA relays

### ISSUE THREAD

**Issue by utoc** [Ellpeck/ActuallyAdditions#187]
Greetings

I've come upon a crash in r57 that didn't appear in r56.

When attaching any Mekanism power conducting cable (conduit) to an AA Energy Relay, there is an immediate crash with the following: http://pastebin.com/sz68A2JQ

I am running FML 2045, AA r57 and Tesla 1.10.2-1.2.1.42.  Reverting to AA r56 alleviates the issue.  Please let me know if I have neglected anything.

**Comment by Ellpeck** [comment]
This is happening due to Mekanism not having updated to the newest version of the  Tesla Mod. 

Technical explanation: [here](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L420), Mekanism tells the Laser Relay that it can accept Tesla, and [here](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L431) it returns itself as a Tesla consumer.
However, now that the Tesla Mod's modid is lowercase since its last update, [this](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L39) won't trigger anymore, meaning the cable actually isn't a Tesla consumer, causing the crash.

You could report this to the Mekanism author or just wait and hope the modid gets updated with the next Mekanism release :)

**Comment by utoc** [comment]
Wow.  Thank you for a thoughtful response.  I really appreciate you taking the time for that.
