### ISSUE TITLE
Bug: Bag does not auto-pickup items when it's in your hand.

### ISSUE THREAD

**Issue by Rated01010010** [Ellpeck/ActuallyAdditions#190]
It works fine, except when it's in your hand, it doesn't auto-pickup items in the whitelist, and auto-pickup is turned on.

**Comment by Rated01010010** [comment]
Also, there seems to be an issue with another mod and your solidified experience. I posted on their GitHub because I'm 99.9% it's the way they code their sample thing, but if you're curious, https://github.com/Ipsis/Woot/issues/83

**Comment by Ellpeck** [comment]
I don't know it doesn't auto-pickup items. Otherwise it would be duplicating them while you had the GUI open, so the solution is just not to make it work when it's in your hand to avoid that. It's way simpler than having it constantly load from NBT every tick it's open :)

Also, I don't know about that other bug, but I'm going to keep an eye out for it.
