### ISSUE TITLE
Fan

### ISSUE THREAD

**Issue by raoulvdberge** [Ellpeck/ActuallyAdditions#327]
For my mob farm I need to push mobs. Something like the OpenBlocks fan would be awesome.

**Comment by Joshwoo70** [comment]
was thinking of 2 variants. stand fan and a hand fan.
* Hand fans use a battery to run 
*Hand fans have a smaller range of 4 blocks while stand fans has a rand of 7 blocks. (feel free to edit the blocks)
*stand fans can be placed while hand fans cannot be.
*stand fans are crafted using a hand fan

(hand fan needs a recipe... any ideas?)

**Comment by Hypsellis** [comment]
It would be awesome to add all the OpenBlocks features in general. ^^

**Comment by Saphrym** [comment]
But do them the AA way. For instance.... instead of a fan.... provide an upgrade to the leaf blower?

**Comment by bookerthegeek** [comment]
Or instead how about making it a gravity well that pulls mobs from a 16 block radius into a 2 block radius around the well (so a 5x5) sort of like the eye of a storm is calm?

**Comment by garantiertnicht** [comment]
Sounds kinda like an *Advanced Magnet* on a powered display stand

**Comment by bookerthegeek** [comment]
Either way, my reasons behind it.

 - Most mob farms on our servers include something along the outside pushing mobs into the middle. So why not just have a "Advanced Magnet" ( I like gravity well better though ) to pull the mobs in?
 - With one block using to move the mobs instead of many it should be less strain on the server. 
 - As for implementation, just set mobs inside the radius of the AM/GW to only want to wander towards the advanced magnet, and set them to wander constantly. This will also stop the issue of fighting entity tracking?

**Comment by PapiDimmi** [comment]
That would be pretty neat. I’m a big _fan_ of this idea.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
