### ISSUE TITLE
Add a performance option to the Empowerer to turn off its Particles

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [Ellpeck/ActuallyAdditions#364]
After upgrading from AA r63 to r71 the performance setting for 'Less Particles' is not being respected. I had turned off particles in r63 despite their awesomeness because they absolutely murder the FPS. Destroyed.

**Comment by Ellpeck** [comment]
I know. It's been removeod. Sorry. :(

**Comment by Ellpeck** [comment]
What particles exactly were the problem anyway?

**Comment by Rumpelstiltskinny** [comment]
not acceptable....the Empowerer particles DESTROY my framerate.

**Comment by Rumpelstiltskinny** [comment]
looks like I'm forced to rollback AA prior to [https://github.com/Ellpeck/ActuallyAdditions/commit/14255ea8019716dbaaee0721bc4ea17df0b1a531](https://github.com/Ellpeck/ActuallyAdditions/commit/14255ea8019716dbaaee0721bc4ea17df0b1a531) or scrap it entirely from my game like YOU did by removing the config setting. Had you considered the possibility that some people actually use the config options before deciding to remove them?

**Comment by Rumpelstiltskinny** [comment]
at what release # did [https://github.com/Ellpeck/ActuallyAdditions/commit/14255ea8019716dbaaee0721bc4ea17df0b1a531](https://github.com/Ellpeck/ActuallyAdditions/commit/14255ea8019716dbaaee0721bc4ea17df0b1a531) become active? I wish to know the latest version that still supports Performance Options.

**Comment by Ellpeck** [comment]
Well I decided to remove them, and I'm sorry, but there's nothing you can do about that. Instead of threatening me with things like "I'm going to have to remove it!!", and blaming me - you could instead be a little more constructive.
Here, how about this: "Could you please add an option to the Empowerer that turns off its particles?"
Because I'd happily do that, if that's something that makes users not be able to run the mod in the best way.

**Comment by Rumpelstiltskinny** [comment]
sounds like a plan....and choosing to remove a mod is MY choice, not a personal threat to you. Also, please do not try to quote something that I did NOT say. What I said was "looks like I'm forced to rollback AA prior to 14255ea or scrap it entirely from my game..." not "I'm going to have to remove it!!".

However, I thoroughly enjoy ActuallyAdditions and would very much like to continue using it. If, and ONLY if it does not negatively impact my game. I would very much appreciate the option to disable particle effects if it helps to make MY gaming experience better for ME. From your mod or any other. I'm not asking for a NEW feature, the old feature (Less Particles) worked perfectly for me.

**Comment by Ellpeck** [comment]
Well, it didn't work perfectly for the server and syncing - that's why I removed it. On a server, only the serverside config decided about the peformance, which to me seemed like a stupid thing. So I removed them.
I can add it back for the Empowerer specifically though, if that's needed.
Also: Don't change back the title :v
