### ISSUE TITLE
[Question] Adding an additional result to crushing an ore

### ISSUE THREAD

**Issue by MysticAura** [Ellpeck/ActuallyAdditions#450]
I'm trying to figure out how to go about adding a chance of zinc to the crushing result of lead ore. Looking at the api I haven't noticed a clear way. Is this possible?

**Comment by Ellpeck** [comment]
Uuuh. You mean to the automatically added one?
No, you can't modify recipes. What you need to do is add this via the API through, for example, [this ](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.java#L127)method, but BEFORE postInit() so that the recipe for zinc doesn't get automatically added :)
