### ISSUE TITLE
Add generic Laser Relay

### ISSUE THREAD

**Issue by dethrasi** [Ellpeck/ActuallyAdditions#463]
o/

Just hoping for block that allows for the relay systems(item\laser\fluid) that would on it's own do nothing, but would allow the relay systems connect through. For example instead of making an extra 10 item relays, laser relays and fluid relays to do nothing but connect between buildings\areas, make some cheaper ones that allow all three relay systems to connect through.

Also mod filter for the item relay system....

**Comment by Ellpeck** [comment]
There IS a mod filter for the Item Relay system..

Also: No, doing this is pretty much impossible, because of how the Laser System works. I'd have to prevent the possibility of this type of connection occuring:
Item - Generic - Energy - Generic - Item,
because that'd allow Energy and Item Networks to connect - which they shouldn't be able to.
Also, it looks less funky to just have one laser instead of multiple ones :P

**Comment by dethrasi** [comment]
ok, thanks for the quick response.

btw great mod =3

**Comment by Ellpeck** [comment]
Thanks :)
Actually, I just realized: I COULD add such a generic Laser Relay - but it still wouldn't be possible to interconnect mutiple networks.
But it'd be cheaper. So I'll do that, probably.

**Comment by Ellpeck** [comment]
Meh. Can't really do this after all sadly :(

**Comment by dethrasi** [comment]
Thanks for trying. I love the mod even without that. =3
