### ISSUE TITLE
Laser Relay invisibility upgrade

### ISSUE THREAD

**Issue by Ellpeck** [Ellpeck/ActuallyAdditions#539]

**Comment by IamAlathe** [comment]
Do I understand this would mean you wouldn't see the red beam?  That would be great for making builds look cleaner.  Might be good to have a way to be able to see them for trouble shooting or setting them up, though.  Like you could see them if you're holding the wrench, but otherwise they would be invisible.  Just my thoughts.  Thanks for all your hard work on this awesome mod. 😄

**Comment by OcAMD** [comment]
Maybe just use the wrench and when you first select it the first click has a visible beam and upon a second click it cycles to an invisible beam mode. If this method is utilized it may be possible to utilize several different beam colors. Maybe a separate tool called a laser lens switcher to cycle various color modes such as red, blue, green, and ultra violet. You could also add ultra violet goggles to view UV beams in case you decide that it may be fun to allow lasers to inflict damage when passed through toggled in the config. Map makers could have a blast with that in adventure maps (even if it was for a security laser turn on or off by redstone).
