### ISSUE TITLE
1.11.2-r96 Raiding Crystallizer's House drops no machines

### ISSUE THREAD

**Issue by revdave33** [Ellpeck/ActuallyAdditions#572]
I was exploring the 1.11.2 mod and was excited when I found the crystalizer's house with some basic Actually Additions machines in there. However, when I tried to break them most of them dropped nothing. The only blocks that dropped anything were the Wood Machine Blocks, the crate, the Compost, the black quartz stair, the colored lamp and the lamp controller. The other machines and blocks just disappeared.

I created the same machine blocks in creative, placed them in survival and they dropped fine when broken.
I used vanilla tools and the Waila display showed them as harvestable.

Actually Additions 1.11.2-r96
forge-13.20.0.2214
Java 1.8.0_25
All downloaded using the Curse launcher

**Comment by garantiertnicht** [comment]
This is intentional and added because of possible balance complains. Its also stated in the [Manual](http://ellpeck.de/actaddmanual/#engineerHouse) and in a tweet from the author which I can't find atm.

**Comment by osirisgothra** [comment]
if you are bent on trying to take such machines, and have mekanism, you can use cardboard boxes to transport the 'fragile' machines home with you, but they seem to retain their fragile-ness even after transport - even in project ozone 3 mythic (the hardest of the three) you can make a wood hammer from the logs on the house, use it on a couple more logs to get sawdust, then use the sawdust right there to make the cardboard box (2x2 crafting grid), which then can claim the machines, works also on the lasers although its kinda pointless since you cant actually use the lasers without a laser wrench, which is a bit more time consuming to make in po3m.
