### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by PwrThruFait** [Ellpeck/ActuallyAdditions#582]
I can not get the "makes you addicted" or "Crystal Clear" achievements. I have done everything the harvest and make the crystals but i never get the achievements. I have checked the other achievements and I have no problem getting the other mods achievements. I am playing on 1.10.2 on Forge 2221

**Comment by IamAlathe** [comment]
I think this issue has existed for a while.  I've noticed it on 1.10, 1.11 and 1.11.2.  I never remember to report it, because achievements are not that big a deal for me.  However, with mods like this, they kind of provide a way to discover what you can do.  Sometimes after getting the next achievement on the list, it pops up, IIRC.

**Comment by leagris** [comment]
Until fixed, an OP in SMP or You in SP with Cheats Enabled, can use these `/achievement give` commands:
```Console
/achievement give achievement.actuallyadditions.makeCrystal [playerName]
/achievement give achievement.actuallyadditions.pickUpCoffee [playerName]
```

**Comment by Ellpeck** [comment]
I don't really understand why this is happening. Is it a 1.10 thing too? The event that I subscibe to to check which item has been picked up always pretends you picked up nothing when it gets called :V

**Comment by leagris** [comment]
1.10 also

**Comment by AEnterprise** [comment]
maybe related to https://github.com/MinecraftForge/MinecraftForge/issues/3419 ?

**Comment by Ellpeck** [comment]
Yea, looks to be. Maybe I'll just swap out the event.
