### ISSUE TITLE
Something strange is going on with Actually Additions and Embers

### ISSUE THREAD

**Issue by elucent** [Ellpeck/ActuallyAdditions#596]
Log: http://pastebin.com/5fi20Q4t

This crash has been replicated by a player on the AllTheMods testing server repeatedly, by entering an RFTools dimension. The specifics of the player's setup are as of yet unknown to me.

Any insight into this bug? I'm not sure if it's me screwing up or you, or possibly both of us.

**Comment by Ellpeck** [comment]
This doesn't have anything to do with either of us. This is the server's watchdog thread crashing, probably because of the server stalling because it was waiting for a tick to happen for too long. 
The stuff in the console is just what appeared to be happening, by coincidence, in the exact moment this happened. Usually, that has basically nothing to do with the actual error itself. 
So probably, something really laggy is going on inside that RFTools dimension.

**Comment by elucent** [comment]
I was considering that, but it does seem a little strange that it's been able to be reproduced so reliably. I'll let whatthedrunk know.

**Comment by Ellpeck** [comment]
Closing this for now.
If this actually doesn't seem to be the watchdog's fault, just reopen the issue.

**Comment by elucent** [comment]
Sounds good.
