### ISSUE TITLE
Duplication Glitch with Item Sack

### ISSUE THREAD

**Issue by RaresKool** [Ellpeck/ActuallyAdditions#616]
A player recently discovered this glitch by accident and reported it to me.
Can I **replicate** it? **Yes!** _**https://youtu.be/OfCL3AoVXMo**_

**How to do it:** 
1. Set the item sack on auto pick up, and whitelist mode with the item of choice.
2. Hold the item you want to duplicate, then drop it. 
3. Upon picking it up you will have it in your inventory but also in your item sack.

**Comment by Ellpeck** [comment]
Try removing mods until this is fixed. It looks like some mod isn't handling the item pickup event properly.

**Comment by RaresKool** [comment]
I will contact the mod author about this. I will also try to get in contact with SpongeForge about this.
On the side note, when this glitch occurs, 1 out of 7 times the server crashes.

**Comment by Ellpeck** [comment]
When using the EntityItemPickupEvent, whichever processing is supposed to happen with the item needs to be cancelled if the event is already set to Event.Result.ALLOW, because otherwise Item Duplication will occur in some cases. I discovered this when working with Forestry, and it seems to be a quirk in the way the event is handled.
Doing something like [this](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/items/ItemBag.java#L75) should fix the issue.

**Comment by RaresKool** [comment]
*Updated my comment above, meant to say modpack not mod*
Another side note. When the Item Sack is set to BlackList mode the glitch does not occur.

**Comment by Ellpeck** [comment]
Closing this because of missing reply.
