### ISSUE TITLE
[Suggestion] Deconstructor

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#682]
I have a suggestion for a block in Actually Additions: the deconstructor.
 
The deconstructor is a block that requires redstone flux (or crystal flux, if in 1.11). It has an expensive recipe (such as a recipe that includes multiple empowered diamatine crystals) and uses a lot of RF in order to deconstruct items, similar to the item repairer, which also has an expensive recipe and uses a lot of RF. You can deconstruct any items, even those added by other mods (and vanilla Minecraft, of course).

_E.g._, you can deconstruct a diamond sword to get two diamonds and a stick back, in exchange for the diamond sword and a lot of RF. The more damaged an item is, the more RF deconstructing it costs.

Other mods have done a similar thing before, such as [this one](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2771389-jglrxavpoks-uncrafting-table), but that has an extremely cheap recipe and does not require any form of energy.

I think this would fit quite well in Actually Additions.

**Comment by Jirajha** [comment]
Yeah, I would love to see one of those.
There are a couple of catches though:

Firstly, what do you return in case the recipe takes a OreDictioniaried Component? 
Sticky Pistons are a good example for that, since they require a Piston and something that is a Slimeball or shares the corresponding OreDictionary entry with it.

Second, what about different crafting recipes for the same thing? 
Books for example require 3 Paper and 1 Leather with the vanilla minecraft recipe.
With Tinkers' Construct you can also make them from Paper and Patterns (aswell as a piece of String I believe). 

Wich brings me to the third point: Possible exploits.
In the above case, with a bit of power, you could turn wood for the patterns into the leather from the other book recipe. If there was a mod that added recipe versions for the same thing, one requiring a diamond, another requiring an emerald, or one requiring an emerald block, the other one a nether star, you could convert the one into the other potentially breaking the barrier the other mod needs to stay balanced.

If the power requirement is static and absurdly high, the potential use for the Deconstructor would be extremely low. Do you really want to use a couple of million RF to extract the Gold Ingot from the Gold Sword from a Zombie Pigman? Or the Iron from the Horse armor you found? Probably not.

If the power requirement is static and low, ... it will become something that is so useful, you basically have to use it as long as there is at least one crafting chain that allows a 'fortunate outcome by using the game mechanics'.

If the power requirement is not static, how do you determine the 'value' of the components in the crafting recipes, especially if the creation of those involves something that is not crafting or harvesting?
That logic alone would require what I personally think was the biggest challenge of EquivalentExchange.
And that was a mod that was 'just' about that value thing alone. And a possible item loss on Deconstucting would be.. while it would make sense..  Meh.. ^^

That said, I would love to see a decent implementation, even if it is limited in what it can do.
I just see too many problems personally. :/

**Comment by elucent** [comment]
Making a universal uncrafter is basically impossible to do if you want a balanced mod. Even making one in the first place is pretty tricky.

A few preset recipes, though, or specifically breaking down certain item classes like tools, could probably work though. With tools you have the advantage of being able to check their repair material, so you don't have to worry about picking a potentially problematic oredict entry. There's a few examples of stuff that uses unconventional repair materials, but in most of those cases, if anything, you _lose_ materials. So it wouldn't break balance or allow dupe bugs.

Just some thoughts.

**Comment by Notawallplan** [comment]
A 50% chance for loss per component of the recipe would help too.

**Comment by Ellpeck** [comment]
_I've decided to stop taking suggestions on this issue tracker. As I don't work on Actually Additions myself anymore and Shadows only maintains the mod, I don't see why they would stick around here cluttering it even though they'll probably never see the light of day._
