### ISSUE TITLE
Auto-Breaker causes java.lang.IllegalArgumentException: Invalid hand null

### ISSUE THREAD

**Issue by sandalle** [Ellpeck/ActuallyAdditions#689]
After updating Actually Additions to 1.10.2-r105, my world crashes with the attached crash reports when the Auto-Breaker.

Minecraft: 1.10.2
Forge Mod Loader: 1.10.2-12.18.3.2239
Actually Additions: 1.10.2-r105
Draconic Evolution: 1.10.2-2.0.8.177
JurassiCraft: 2.0.5
Nether Metals: 1.10.2-1.1.3

Auto-Breaking Amber Ore from JurassiCraft (not added by Nether Metals):
[crash-2017-03-13_10.20.21-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/839076/crash-2017-03-13_10.20.21-server.txt)

AutoBreaking Ender Draconium Ore or Nether Draconium Ore from Draconic Evolutions:
[crash-2017-03-13_09.54.54-server.txt](https://github.com/Ellpeck/ActuallyAdditions/files/839075/crash-2017-03-13_09.54.54-server.txt)

**Comment by Ellpeck** [comment]
This is an issue with Nether Metals due to the fact that it uses the parameter swingingHand in its code [right here](https://github.com/MinecraftModDevelopmentMods/NetherMetals/blob/master1.10/src/main/java/com/mcmoddev/nethermetals/NetherMetals.java#L94), even though a player (especially a fake player) breaking something doesn't necessarily mean that they are swinging their arm while doing it. The mod should instead use EntityPlayer.getHeldItemMainhand().

**Comment by sandalle** [comment]
Thank you. :) I found someone opened a similar bug with Nether Metals after I did this one at https://github.com/MinecraftModDevelopmentMods/NetherMetals/issues/20 . I thought it might be Actually Additions as the Auto-Breaker also crashed with non-Nether Metal ores (e.g. Amber Ore from JurassiCraft) while in the Overworld. Breaking the same blocks I listed above by hand (player with Tinker's Construct pickaxe) worked without issue.
