### ISSUE TITLE
[1.11.2-r106] "Colored tooltips" being off doesn't seem to affect HWYLA or chat (JEI?)

### ISSUE THREAD

**Issue by starg09** [Ellpeck/ActuallyAdditions#701]
I disabled this on our pack _(yeah, I know... I'm really fun at parties)_. Anyway, noticed two things while debugging today:

* HWYLA still shows the name of everything from the mod with a gray colour (unlike everything else, which has a white one).
* When giving something to myself through creative, the message that shows up on chat will name the item using a purple colour. Thinking about it while writing this, I noticed this might be when giving through JEI only (didn't test with a `/give` command).

**Comment by Ellpeck** [comment]
I don't care, to be honest. 
It was a joke feature to mock everyone who wants to turn off colored item names. I don't plan on making it work properly :^)

**Comment by starg09** [comment]
Welp.

Nothing against it, to be honest. Simply would prefer most of the stuff to behave similarly for the player, specially stuff they'll find in early game even. Wouldn't mind the most advanced stuff to show it, since others mods also do it at that point (IIRC?)

At least you give me another argument I can give elucent about replacing HWYLA for TOP, so thanks :^)

**Comment by Ellpeck** [comment]
To actually clear this up, by the way, I use the ItemTooltipEvent and just add TextFormatting.RESET to the start of the tooltip string. HWYLA probably doesn't use that event.

**Comment by starg09** [comment]
Yeah, I imagined so. OP was meant more as a "it would be nice if it covered HWYLA as well, if possible".

Should have named it as a request more than a bug... Not like it would've made much difference, I imagine :P

**Comment by TehNut** [comment]
https://github.com/TehNut/HWYLA/blob/754d9c0fb7353a5a8f105a87c063e2199d8775d3/src/main/java/mcp/mobius/waila/overlay/DisplayUtil.java#L186-L207

Here's a quick breakdown of how Waila grabs the name:

1. Waila calls `ItemStack#getTooltip(...)`
2. The first line gets prefixed with the `EnumRarity` text color.
3. In the second highlighted method in that link, the first line of the tooltip gets prefixed with the custom block name color (default being white).

I wonder if this is because you're using `RESET` and not `RESET + WHITE`. I'll look into it a bit.

**Comment by Ellpeck** [comment]
My method was a derpy workaround anyway, because this is a joke feature more than it is anything else x)
