### ISSUE TITLE
Crystal Flux for 1.10.X?

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#707]
Will change from RF to CF ever be backported to 1.10, or is that only for 1.11 permanently?

**Comment by Ellpeck** [comment]
no, and yes

**Comment by PapiDimmi** [comment]
Why not? :/ I like CF.

**Comment by Ellpeck** [comment]
There will be as little feature updates for 1.10 as possible. It's outdated.
Also, CF doesn't exist. It's just the way that the energy is displayed. There's no API or anything for it, so it'd just be a waste of time to backport it.

**Comment by PapiDimmi** [comment]
I know that there is no major difference to CF, but I like the way the colours change. It’s nice.

Since there’s such little differences, backporting would take little effort, no?

And no, 1.10 is not outdated. 1.11 is not stable; most mods for 1.11 are in alpha or beta and have a lot of bugs. Additionally, there are very few mods and modpacks available for 1.11. 1.10 is considered the latest “stable” release for mods, like 1.7.10 was back in the day (heck, some people still play 1.7.10).

**Comment by Ellpeck** [comment]
1.10 is outdated.

**Comment by Ellpeck** [comment]
There is no such thing as a "stable release for mods". The best version to mod on is always the newest, no matter the circumstance and surroundings. If you don't stay on the newest version with your mod, in my opinion, you're doing something wrong.

**Comment by PapiDimmi** [comment]
I _am_ using the latest version of your mod; or the latest version for 1.10.2, at least. Naturally, I can’t use the 1.11.2 version of your mod when I’m playing on 1.10.2.

I am playing the ”FTB Presents Direwolf20 1.10” pack, which is, obviously, not for 1.11. There aren’t many mods for 1.11 yet; most mods, including almost all the big ones (such as Tinkers’ Construct, Immersive Engineering, EnderIO, IndustrialCraft2, and so on), are not updated for 1.11, and I can’t play on 1.11.2 without them.

Most mod developers backport new features because they know that not everyone instantly updates to the newest version of the game when it’s available. It takes time for mods to be updated.

**Comment by Ellpeck** [comment]
The only reason that the newest version of the game is not also the most recent version for mods is because too many people think "The other people are staying, so I am staying to".
If more big mods were to take the step and move on, so would all smaller mods and so would all the players.
It's untrue, from what I've personally found out over the years, that it the long time it takes mods to update is the reason for the delay. The actual reason is that people just don't want to update, for whatever reason. I think this is an unnecessary thing.
Also, I'm sorry but I'm not willing to discuss stuff like this in an unrelated Github issue. Locking the thread.
