### ISSUE TITLE
Machines should probably be in pulse mode by default

### ISSUE THREAD

**Issue by PapiDimmi** [Ellpeck/ActuallyAdditions#725]
When you place a machine, it’ll start functioning immediately, so the atomic reconstructor will continuously fire its laser, and the automatic precision dropper will keep dropping items. Wouldn’t it be more neat if pulse mode were the default mode?

**Comment by Ellpeck** [comment]
I disagree, sorry.

**Comment by PapiDimmi** [comment]
When you place a machine, naturally, you don’t want it to start doing stuff until you’re finished with your contraption, right? Doesn’t that make sense?

**Comment by Ellpeck** [comment]
The nature of the machines activating right away is a great gameplay mechanic for those unsure about how they work. 
No one ever wondered how to use the Atomic Reconstructor because immediately when they placed it down, they found out what its function is and how it works.
I'm not willing to sacrifice that.

**Comment by PapiDimmi** [comment]
People should learn how to use the mod via wikis, videos, and the in-game manual, not by randomly placing blocks and seeing what happens.

Besides, the atomic reconstructor won’t do anything until it has a source of power, and if the player knows how to generate RF and use it for machines, he or she probably knows how Actually Additions works. It’s just a big waste of RF; if you don’t have a redstone torch ready, you’ll have to disconnect the power or remove the machine, which is just a hassle.
