### ISSUE TITLE
BlockBreakers compatability with Anti griefing

### ISSUE THREAD

**Issue by Raycoms** [Ellpeck/ActuallyAdditions#742]
Currently the ActuallyAdditions block breakers do not work together with our mods anti griefing (minecolonies).

We had some contact with forge and they meant, fake players are meant to use the players UUID.

**Comment by Ellpeck** [comment]
That doesn't seem very realistic.
The breakers would have to track which player placed them and then create a fake player based on that player's UUID. That would be impossible for things like a placer placing a breaker, because there would be either not assignable player, or a different fake player's UUID would be assigned to the breaker.
The way I do it right now, using the default Minecraft fake player, is how most other mods do it.

**Comment by Raycoms** [comment]
The problem with this is that anti griefing gets completely exposed.
If a player allows 1 placer or breaker to work he would allow any player to
make a placer or breaker work inside his claim.

2017-04-08 13:26 GMT-03:00 Ellpeck <notifications@github.com>:

**Comment by Raycoms** [comment]
If your placer has the players UUID the breaker he places would inherit his
UUID.

2017-04-08 13:59 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:
