### ISSUE TITLE
Buttons bug with BungeeCord

### ISSUE THREAD

**Issue by mkrtes** [Ellpeck/ActuallyAdditions#814]
There is one strange problem, that I don't know where to write. When I use bungeecord for sponge-server there was a problem with mod ActuallyAdditions. Interface buttons don't work. I run server only with sponge - it works well. Once connect with bungee - buttons not working. Something similar was discussed here: SpongePowered/SpongeForge#1394 I don't know what to do and who to contact...

**Comment by Ellpeck** [comment]
I don't support Sponge, sorry.

**Comment by kaal-1** [comment]
I think it may not have anything to do with sponge, since it only happens when using bungeecord.
Similar problems occurred in the past with other mods, thaumcraft being one big example. It had something to do with packets/entity ids. Take a look at https://github.com/SpongePowered/SpongeForge/issues/731 if you may..
