### ISSUE TITLE
AA Magnet wont recharge from TE Capacitor

### ISSUE THREAD

**Issue by Zetharion** [Ellpeck/ActuallyAdditions#848]
Ok not entirely sure who this is on, but the AA drill will recharge from a TE Flux Capacitor that is in my hotbar but the AA magnet does not.  I provided the RedstoneFlux version just in case that is helpful.

Actually Additions: 1.12-r115
Thermal Expansion: 1.12-5.3.2.10
Redstone Flux: 1.12-2.0.1.2

**Comment by Shadows-of-Fire** [comment]
This is on Thermal's end, last I checked they were not properly looking for the Forge Energy item capability.  It also has the effect that the Energetic Infuser will not charge AA (or any FE-based) Items.

**Comment by Ellpeck** [comment]
Paging @KingLemming about this

**Comment by Shadows-of-Fire** [comment]
I've mentioned this to KL before about the infuser, but I hadn't mentioned the Flux Capacitor, as I am actually using one right now with no issues... (in atc)

**Comment by KingLemming** [comment]
@Shadows-of-Fire - you are only somewhat correct there. The code is in the infuser and we ARE supporting Forge Energy.

The issue was that the Infuser didn't accept non-RF stuff in the GUI. It could be inserted via automation though. But that's been fixed.

I think the issue here may be simply that the capacitor doesn't charge things "in the hotbar," only held and worn items, and it sounds like the item isn't being held.

**Comment by Ellpeck** [comment]
Closing this for now as it seems like user error.
