### ISSUE TITLE
[Suggestion/Request] Add config option to disable disruption mode on atomic reconstructor

### ISSUE THREAD

**Issue by CuriousHP** [Ellpeck/ActuallyAdditions#854]
Hello, I would like to request config option to have ability to disable disruption mode on atomic reconstructor. I know it's an easter egg, and not many know about it, but could you please add option for that. It's kind of an issue in some packs, people who know about this "feature" can bypass most progression.
One exmaple is ATM expert. So if you decide to do that, it would be greatly appreciated.

**Comment by MigukNamja** [comment]
Ah, cool. I see you fixed this 2 days ago:

https://github.com/Ellpeck/ActuallyAdditions/pull/851

Thanks :-)

**Comment by MigukNamja** [comment]
I would greatly appreciate a 1.10.2 build with this change in it. Indeed, I would not be opposed *at all* to 1.10.2-r105 with just this 1 change/fix on top. But, I'll be just as happy with a 1.10.2 build with everything appropriate in it.

I run the ATM:E "Official" server and CuriousHP is a long-time player on the server. He confirmed the Easter Egg in 1.10.2-r105.

**Comment by RoyCurtis** [comment]
Disappointing that this misfeature exists in the first place, let alone the issue is closed. [There is a mod that is supposed to fix this](https://minecraft.curseforge.com/projects/aarandomlensblocker-actually-additions-addon/files/2455077), but it has no effect for us (FTB Beyond 1.10.1).

For the developer and other mod devs who happen to be reading; _please_ don't code dumb "easter eggs" like this without at least a config option in the first place. I appreciate that it's difficult to maintain multiple versions and backport fixes, but as a server admin it sucks to have to try patch cheats like this, when they _eventually_ come to light.

**Comment by Shadows-of-Fire** [comment]
I mean, just don't play 1.10 and you wouldnt have these problems

**Comment by Ellpeck** [comment]
I love how butthurt everyone is about this, it's so amazing :^)
