### ISSUE TITLE
Potions Rings Nerf

### ISSUE THREAD

**Issue by silentdragon14** [Ellpeck/ActuallyAdditions#977]
I think the change to require blaze powder to charge the rings makes then not worth using.  I'd suggest either a harder recipe and free usage again, or make each blaze powder last longer than 1 second.  I can't be bothered to bring thousands of blaze powders with me on a mining trip for my Haste and/or Night Visions rings.

**Comment by silentdragon14** [comment]
WTH?  Instant closing with no explanation?

**Comment by Shadows-of-Fire** [comment]
ye

**Comment by canitzp** [comment]
The change from nothing to blaze powder is a good choice and much better than an harder recipe. If you use the rings, at the state in the game where they are designed for, then high amounts of blaze powder shouldn't be a problem anymore.
I hope this is a better answer than Shadows

**Comment by Ellpeck** [comment]
Hey. This issue got closed because we don't currently take suggestions. Additionally, I think the concept of the rings in general is not very balanced or reasonable, which is why I made them require that much Blaze Powder. I wanted to remove them, but a lot of players told me that they'd be really sad about that, so I just decided to take this kind of weird mid-way approach.
I'm going to leave this thread locked as we currently don't take suggestions.
