### ISSUE TITLE
[Suggestion] Machine upgrades

### ISSUE THREAD

**Issue by Dimentive** [Ellpeck/ActuallyAdditions#983]
I don’t know if this has been suggested before, but a way to upgrade the crusher, empowerer, powered furnace, etc. would be really neat.

There could be the basic speed and efficiency upgrades. Nothing too fancy.

**Comment by MarikCZ** [comment]
I thinks that better to add my idea there, than create new suggestion...

Vertical Digger

There are some upgrades for mining drill. Drill is used to craft vertical digger. Once I use drill to craft digger, I cant get it back, (likes as in IC2) and use for mining. Only way is craft new - this is not problem.
Problem that I have is, when I use drill to mining I can add some updates, like as fortune or silk touch, but digger hasn't this option - maybe it is so "cheaty", but I really prefer ores in natural form (silk touch).
I didn't use phantom boosters, but I read, that they can be used up to 3 on digger, to increase mining area. What about reform of boosters and upgrades? Think that I missing is not only "upgradable/enchantable" diggers, but some upgrade (option for phantom booster) that can increase internal storage, mining speed (save actual speed as maximum, be cause of lagging) or some utilities, like as torching in mined veins (there are monsters spawning, and traps are not effective), or pulling ores in chest near it.

Laser between relays

I read, that in older version were laser visible only when wearing engineers glasses - can you make option (in configs) to bring this back? Or some "key" as in Storage Drawers to hide them, because I notice FPS drops and lags since using them. Maybe you can add some blocks (pipes) that can transfer energy for short distance - making webs on back side of machines is really annoying.

Cells, Energy Cubes (Banks)
Header says "all" - really miss them. Maybe tired as crates. (Classic, energized and empowered)

Multi-relays
What about relays that can be used like as all three types? Even you can make redstone lasers etc., like as wires in immersive engineering.

Hoppers
Really miss hoppers, that can transfer items to up side, and hoppers with more than one out.

Canola
Can you make on wiki canola effectiveness table? Like as 1 Farmer can support 4 pressers, 1 presser can supply 2 fermenters, and what if use greenhouse glasses or boosters from mystical agriculture,

Applied Energistic
Crusher can double certus quatrz.

At end, I must say, that I know that many ideas are "copied" from other mods, but thats your decide if you make it or not. And please excuse for grammar. I have headache, and I don't want to check it all. ;-)
