### ISSUE TITLE
Firework box recipe not working.

### ISSUE THREAD

**Issue by jusjudge** [Ellpeck/ActuallyAdditions#988]
Minecraft ver: 1.12.2
Forge ver: 14.23.1.2575
Actually Additions ver: 1.12.2-r126

The title basically says it all but I am trying to craft the firework box but the recipe doesn't work in a crafting table (Vanilla), a crafting station (Tinker's Construct), nor a crafting grid (Refined Storage).

**Comment by YasminEndusa** [comment]
Have you checked with JEI if the recipe has been changed?

**Comment by canitzp** [comment]
Like you can see here: http://puu.sh/yW7VO/4b646d2273.jpg The Firebox has a recipe, if it hasn't for you then the recipe for it is disabled in the modpack

**Comment by JoeSGT** [comment]
@canitzp  it wont craft like that because you need firework which does not show that in Jei
here the what i had found
https://github.com/Ellpeck/ActuallyAdditions/blob/d9b6838df9363eaaf2e2ba2bcda574b70323e218/src/main/java/de/ellpeck/actuallyadditions/mod/crafting/BlockCrafting.java#L151
by putting firework it will work without it well look
https://gyazo.com/543d3a1660a7d81d611505fb9e8b692e this image show that i attempt to craft it with having default config and running the mod alone without a pack just running the actuallyadditions  it does not work
now i put a crafted firework https://gyazo.com/429a43f2d7c87044c85207fbb9086f32
and you can see that i can craft it

**Comment by canitzp** [comment]
@mezz is there a problem with JEI, so that it won't show firework in crafting recipes?

**Comment by mezz** [comment]
I'm not sure, I haven't done anything with fireworks in JEI.

**Comment by canitzp** [comment]
That is more like a patch to fix something that isn't a problem on AA side. Since the recipe does work like a charm and only JEI ist showing the recipe wrong
